export enum Keyword {
    Class = "Class",
    Constructor = "constructor",
    Function = "function",
    Method = "method",
    Field = "field",
    Static = "static",
    Var = "var",
    Int = "int",
    Char = "char",
    Boolean = "boolean",
    Void = "void",
    True = "true",
    False = "false",
    Null = "null",
    This = "this",
    Let = "let",
    Dio = "dio",
    If = "if",
    Else = "else",
    While = "while",
    Return = "return",
}
