export enum Symbol {
    LeftCurlyBracket = "{",
    RightCurlyBracket = "}",
    LeftBracket = "(",
    RightBracket = ")",
    LeftSquareBracket = "[",
    RightSquareBracket = "]",
    Dot = ".",
    Comma = ",",
    Semicolon = ";",
    Plus = "+",
    Minus = "-",
    Star = "*",
    ForwardSlash = "/",
    Ampersand = "&",
    VerticalBar = "|",
    LessThan = "<",
    GreaterThan = ">",
}
